// <auto-generated />
using System;
using HandsOnApiUsingEF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HandsOnApiUsingEF.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20191113045420_Mig1")]
    partial class Mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HandsOnApiUsingEF.Models.Department", b =>
                {
                    b.Property<string>("Did")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeptName")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("Did");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("HandsOnApiUsingEF.Models.Employee", b =>
                {
                    b.Property<int>("Eid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desig")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Did")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EName")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Sal")
                        .HasColumnType("float");

                    b.HasKey("Eid");

                    b.HasIndex("Did");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("HandsOnApiUsingEF.Models.Employee", b =>
                {
                    b.HasOne("HandsOnApiUsingEF.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("Did");
                });
#pragma warning restore 612, 618
        }
    }
}
